#ifndef STATE_MANAGER_H_
#define STATE_MANAGER_H_

enum {
  GAMESTATE_STARTUP,
  GAMESTATE_MAIN,
  GAMESTATE_STATS,
  GAMESTATE_FOOD,
  GAMESTATE_BATH,
  GAMESTATE_SPORT,
  GAMESTATE_INTERACTION,
  GAMESTATE_MEDECINE,
  GAMESTATE_LIGHT,
  GAMESTATE_TIME,
  GAMESTATE_EXIT
};

void set_sate_GAMESTATE_MAIN();
void set_sate_GAMESTATE_STATS();
void set_sate_GAMESTATE_FOOD();
void set_sate_GAMESTATE_BATH();
void set_sate_GAMESTATE_SPORT();
void set_sate_GAMESTATE_INTERACTION();
void set_sate_GAMESTATE_MEDECINE();
void set_sate_GAMESTATE_LIGHT();
void set_sate_GAMESTATE_TIME();

#endif /* !STATE_MANAGER_H_ */
